name: NPM Publish @viamrobotics/sdk

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: [x64, qemu-host]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install, Build, and Publish
        run: |
          sudo chown -R testbot .
          sudo -u testbot bash -lc 'make build'
          npm install -g @jsdevtools/npm-publish
          npm-publish --token=${{ secrets.NPM_TOKEN }}
