name: Pull Request Update

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    uses: viamrobotics/viam-typescript-sdk/.github/workflows/test.yml@main
